# All
- hosts: cloud.*, edge.*
  vars:
    container_name: "fl-container"
  prepare:
    - include_vars: "{{ scenario_dir }}/vars/vars.yaml"

    - name: Copying files
      synchronize:
        src: '{{ artifacts_dir }}/'
        dest: '/tmp/app/'
      delegate_to: "{{ inventory_hostname }}"

    - name: Checking Docker Installation
      command: docker --version
      register: docker_valid
      ignore_errors: yes
    - name: Installing docker
      shell: '/grid5000/code/bin/g5k-setup-nvidia-docker'
      when: docker_valid.failed
    - name: Loading docker image
      shell: 'docker load < /tmp/app/gpu-docker.tar'
    - name: Running docker image
      shell: 'docker run --network=host --gpus all --name {{ container_name }} -t -d gpu-docker'
    - name: Copy local files to docker container
      shell: 'docker cp -a /tmp/app/. fl-container:/app/artifacts/'
    - name: Mkdir
      shell: 'docker exec fl-container bash -c "mkdir -p /tmp/app/data/"'
    - name: Mv PACS dataset
      shell: 'docker exec fl-container bash -c "mv /app/artifacts/data/PACS /tmp/app/data/."'
    - name: Generating partitions
      shell: 'docker exec -t {{ container_name }} python3 /app/artifacts/data_preparation/PACS.py --n_partitions {{ total_num_clients // 4}} --alpha {{ alpha }}'
  

# Server
- hosts: cloud.FLServer.*
  vars:
    container_name: "fl-container"
    log_dir: "{{ container_name }}:/app/fl_logs/"
    save_dir: "/home/cprigent/runs/last/"
  prepare:
    - name: Mkdir
      shell: 'mkdir -p /app/fl_logs'
    - name: Starting Tensorboard
      shell: 'docker exec -t -d {{ container_name }} python3 -m tensorboard.main --logdir /app/fl_logs'

  launch:
    - include_vars: "{{ scenario_dir }}/vars/vars.yaml"
    - debug:
        msg: "Starting FLServer: {{ _self.url }}"
    - shell: 'sudo docker exec -t {{ container_name }} python3 /app/artifacts/server.py
              --server_address {{ _self.url }}:8080
              --strategy {{ strategy }}
              --model {{ model }}
              --num_rounds {{ num_rounds }}
              --min_available_clients {{ min_available_clients }}
              --min_fit_clients {{ min_fit_clients }}
              --fraction_fit {{ fraction_fit }}
              --local_epochs {{ local_epochs }}
              --n_clusters {{ n_clusters }}
              --dataset {{ dataset }}
              --compression {{ compression }}
              --total_num_clients {{ total_num_clients }}
              --transforms {{ transforms }}'
      async: "{{ async }}"
      poll: 0
    - debug:
        msg: "Starting FLClient: server at {{ _self.url }}"
    - shell: "{% for thishost in play_hosts %}
                {% if inventory_hostname==thishost %}
                    sudo docker exec -t -e CUDA_VISIBLE_DEVICES={{ item // (n_client_server_node // 2) }} {{ container_name }} 
                    python3 /app/artifacts/client.py
                    --server_address {{ _self.url }}:8080
                    --model {{ model }}
                    --client {{ client }}
                    --compression {{ compression }}
                    --path_to_encoder_weights {{ path_to_encoder_weights }}
                    --dataset {{ dataset }}
                    --randomized_quantization {{ randomized_quantization }}
                {% endif %}
              {% endfor %}"
      async: "{{ async }}"
      poll: 0
      loop: "{{ range(0, n_client_server_node)|list }}"

  finalize:
    - name: Retreiving log files
      shell: "sudo docker cp {{ log_dir }} {{ save_dir }}"
    - debug:
        msg: "Stop and remove container"
    - shell: "docker stop {{ container_name }}"
    - shell: "docker rm {{ container_name }}"

# Clients
- hosts: edge.FLClient.*
  depends_on:
    service_selector: "cloud.FLServer.*"
    grouping: "round_robin"
    prefix: "server"
  vars:
    container_name: "fl-container"

  launch:
    - include_vars: "{{ scenario_dir }}/vars/vars.yaml"
    - debug:
        msg: "Starting FLClient: server at {{ server.url }}"
    - shell: "{% for thishost in play_hosts %}
                {% if inventory_hostname==thishost %}
                  sudo docker exec -t -e CUDA_VISIBLE_DEVICES={{ item // (n_client_per_node // 2) }} {{ container_name }} 
                  python3 /app/artifacts/client.py
                  --server_address {{ server.url }}:8080
                  --model {{ model }}
                  --client {{ client }}
                  --compression {{ compression }}
                  --path_to_encoder_weights {{ path_to_encoder_weights }}
                  --dataset {{ dataset }}
                  --randomized_quantization {{ randomized_quantization }}
                {% endif %}
              {% endfor %}"
      async: "{{ async }}"
      poll: 0
      loop: "{{ range(0, n_client_per_node)|list }}"

  finalize:
    - debug:
        msg: "Stop and remove container"
    - shell: "docker stop {{ container_name }}"
    - shell: "docker rm {{ container_name }}"
